### PR TITLE
remove CellPositionsHCalBarrelPhiThetaSegTool

### PR DESCRIPTION
**Pull request by giovannimarchiori**
BEGINRELEASENOTES
- Remove CellPositionsHCalBarrelPhiThetaSegTool, superseded by CellPositionsHCalPhiThetaSegTool (see  #https://github.com/HEP-FCC/k4RecCalorimeter/issues/112)
ENDRELEASENOTES

### CODE REVIEW

**Comment by giovannimarchiori** [comment]
Remaining places using the old tool:

[BrieucF/LAr_scripts](https://github.com/BrieucF/LAr_scripts) · [FCCSW_ecal/run_thetamodulemerged.py](https://github.com/BrieucF/LAr_scripts/blob/1ecfbcec009fac1483141819425b8aaeda3d01ed/FCCSW_ecal/run_thetamodulemerged.py#L530)
=> easy to fix, but discontinued - not worth it?

[HEP-FCC/fcc-tutorials](https://github.com/HEP-FCC/fcc-tutorials) · [full-detector-simulations/FCCeeGeneralOverview/run_ALLEGRO_RECO.py](https://github.com/HEP-FCC/fcc-tutorials/blob/babd9ebd04f07819d0a29b6716e8675ca3a975d3/full-detector-simulations/FCCeeGeneralOverview/run_ALLEGRO_RECO.py#L219)
=> the tutorial script is anyway out of sync with the latest version of run_ALLEGRO_RECO.py (which I plan to update soon) so we'd rather update the tutorial when it's time for another round of tutorials

[HEP-FCC/FCC-config](https://github.com/HEP-FCC/FCC-config) · [FCCee/FullSim/ALLEGRO/ALLEGRO_o1_v02/run_digi_reco.py](https://github.com/HEP-FCC/FCC-config/blob/d0936e4da154dc316a1788d8783c84b1ac7ca735/FCCee/FullSim/ALLEGRO/ALLEGRO_o1_v02/run_digi_reco.py#L199)
=> v02 is superseded by v03, but maybe we want to keep the possibility to run the reconstruction code for it? In that case I can fix this in a quick little PR

**Comment by giovannimarchiori** [comment]
@BrieucF or @kjvbrt do you have ny feedback?
Thanks
    Giovanni

**Comment by kjvbrt** [comment]
Hi @giovannimarchiori, I'm fine with removal, just keep ALLEGRO_o1_v02 running :)

How about using the ALLEGRO script directly from FCC-config in the tutorial(s)?

**Comment by giovannimarchiori** [comment]
Hi @kjvbrt 
so this https://github.com/HEP-FCC/FCC-config/pull/218 will make ALLEGRO_o1_v02 run with the change in this PR.
About the tutorial - I think we should update it to use the latest developments. Give me some time while we try to wrap up a few things and update the official ALLEGRO script in FCC-config, and then we could use that also in the tutorials.
Please let me know if this is enough for merging this PR and https://github.com/HEP-FCC/FCC-config/pull/218
Cheers,
   Giovanni

**Comment by kjvbrt** [comment]
Ok, looks good to me :)

**Pull request merged**
