### PR TITLE
Changes to support reconstruction of "turbine" endcap ECal

### PR DESCRIPTION
**Pull request by varnes**
A few changes needed to support the turbine endcap ECal geometry:

- add kEndcapTurbine to enumerated segmentation types, and add code for handling that segmentation (detectorSegmentations/FCCSWEndcapTurbine_k4geo.h)
- generalize the Segmentation pointer type in a few places
- use cellTheta rather than segmentation->theta(cell.getCellID()) in CaloTowerToolFCCee::CellsIntoTowers

Note that this request must be merged at the same time as my request for k4geo.

### CODE REVIEW

**Comment by giovannimarchiori** [comment]
Hi @varnes , is there a reason for removing the handling of the phi-theta grid segmentation? I understand that you want to add support for the turbine segmentation, but why removing that for phi-theta grid, which AFAIK is currently used for the HCAL clustering?

**Comment by giovannimarchiori** [comment]
Also, I see that now this section is commented
```
  // 4. HCAL barrel
  const edm4hep::CalorimeterHitCollection* hcalBarrelCells = m_hcalBarrelCells.get();
  debug() << "Input hadronic barrel cell collection size: " << hcalBarrelCells->size() << endmsg;
  // Loop over a collection of calorimeter cells and build calo towers
  if (m_hcalBarrelSegmentation != nullptr) {
    CellsIntoTowers(aTowers, hcalBarrelCells, m_hcalBarrelSegmentation, m_hcalBarrelSegmentationType, fillTowersCells);
    totalNumberOfCells += hcalBarrelCells->size();
  }
```

So this PR implements clustering for ECAL endcap but breaks that for HCAL barrel, clearly not an ideal solution. It should be possible to have both, by restoring the previous code handling the phi-theta grid segmentation.

**Comment by varnes** [comment]
Hi Giovanni,

  That certainly wasn't an intentional change on my part -- that section of code was commented out in the main branch when I created the fork for my development.  Brieuc has asked me to make sure that all of the changes that have occurred in the main branch be incorporated into my fork;  I will do that and then create a new pull request (meaning that you [or I?] can close this one).

Best regards,
Erich

**Comment by giovannimarchiori** [comment]
Thanks Eric! 
I am sure this was not intentional. 
I am not sure why this was commented out , probably you started from an old version some months ago, in between there were some PR in which the clustering for phi-theta for HCAL was implemented. Make sure that you rebase your code so that you pick up all latest developments.
About this PR, you can close it or you can also mark it as Draft, and update it later and unmark it when ready
Thanks for this important piece of code!

**Pull request closed without merging**
